// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// // src/app/layout.js
import "./globals.css";

export const metadata = {
  title: "Materials Lab Inc.",
  description: "Advanced testing and analysis services",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-gray-50 text-gray-800 font-sans">
        <header className="bg-blue-950 text-white p-6 shadow-lg ">
          <nav className="max-w-7xl mx-auto flex justify-between">
            {/* <h1 className="text-3xl font-bold">Materialslab Inc.</h1>
            <p className="text-sm">Testing & Analysis Services</p> */}
            <div>
            <h1 className="text-3xl font-bold">Materialslab Inc.</h1>
            <p className="text-sm mt-1">Testing & Analysis Services</p>
            </div>
            <div className="space-x-4 items-center">
              <a href="/" className="text-2xl hover:underline">Home</a>
              <a href="/services" className="text-2xl hover:underline">Services</a>
              <a href="/contact" className="text-2xl hover:underline">Contact</a>
            </div>
          </nav>
        </header>
        <main className="py-6 px-4 max-w-7xl mx-auto">{children}</main>
        <footer className="bg-blue-800 text-white p-4 text-center mt-10">
          © {new Date().getFullYear()} Materials Lab Inc. All rights reserved.
        </footer>
      </body>
    </html>
  );
}

